name: Code Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
